---
title: "Hamburg_Fuhlsbüttel"
author: "Mandar"
date: "2024-09-26"
output: 
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
---

```{r}
knitr::opts_chunk$set(cache = TRUE, cache.lazy = FALSE, warning = FALSE,
                      message = FALSE,echo = TRUE, dpi = 360, warning = FALSE,
                      fig.width = 15, fig.height = 10)

```



```{r}
library(dplyr)
library(SPEI)
library(kableExtra)
library(readxl)
library(readr)
library(writexl)
library(tidyr)
library(tidyverse)
library(scales)
library(ggplot2)
library(plotly)
library(timetk)
library(broom)
library(trend)
library(lubridate)
library(trend)
library(Kendall)
library(ggtext)

```

## Reading the data from the folder

```{r}
observational_data_1936_2024 <- read.delim("/Users/mandarphatak/Climate-Analysis/DWD_Folder/Data_DWD/tageswerte_KL_01975_19360101_20241231_hist/produkt_klima_tag_19360101_20241231_01975.txt", sep = ";") |> 
  mutate(MESS_DATUM = ymd(MESS_DATUM))



## Updated Data 

observational_data_updated <- read.delim("/Users/mandarphatak/Climate-Analysis/DWD_Folder/Data_DWD/tageswerte_KL_01975_akt/produkt_klima_tag_20231126_20250528_01975.txt", sep = ";") |> 
  mutate(MESS_DATUM = ymd(MESS_DATUM)) |> 
  filter(MESS_DATUM > "2024-12-31")

# Combining the data

data <- observational_data_1936_2024 |> 
  rbind(observational_data_updated)

# Data Cleaning
data <- data |> rename(date = MESS_DATUM,prec = RSK, vapour_press = VPM, mean_press = PM,
         rel_hum = UPM, Tavg = TMK, Tmax = TXK, Tmin = TNK) |>
  mutate( prec = ifelse(prec == -999, NA, prec)) |>
  select(date,prec,vapour_press,mean_press,rel_hum,Tavg,Tmax,Tmin)

write_rds(data, "/Users/mandarphatak/Climate-Analysis/DWD_Folder/Data_DWD/Hamburg_Fuhlsbüttel.rds")
```

#### 

